workflows:
  android-debug:
    name: LifeSphere OS Build
    max_build_duration: 60

    environment:
      java: 17

    scripts:

      - name: Make gradlew executable
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build APK (skip tests)
        script: |
          ./gradlew assembleDebug -x test

    artifacts:
      - app/build/outputs/**/*.apk
