workflows:
  android-debug:
    name: LifeSphere OS Build
    max_build_duration: 60

    environment:
      java: 17

      vars:
        PACKAGE_NAME: "com.nexvora.lifesphereos"

    scripts:

      - name: Checkout
        script: |
          git clone $CM_REPO_URL .

      - name: Make gradlew executable
        script: |
          chmod +x gradlew

      - name: Clean
        script: |
          ./gradlew clean

      - name: Build Debug APK (skip tests)
        script: |
          ./gradlew assembleDebug -x test

    artifacts:
      - app/build/outputs/**/*.apk
